In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
%matplotlib inline

In [6]:
data = loadmat("E:\MLNEW _BTM\data\ex3data1.mat")

In [32]:
X[0,0]


0.0

In [33]:
X.shape

(5000, 400)

In [31]:
X= data['X']
y = data['y']

In [34]:
X.shape , y.shape

((5000, 400), (5000, 1))

In [35]:
 X = np.insert(X,0,1,axis=1)

In [36]:
X[0,0],X[1,0]

(1.0, 1.0)

In [37]:
np.unique(y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [38]:
X.shape

(5000, 401)

In [58]:
X = np.matrix(X)
y = np.matrix(y)

In [59]:
theta = np.matrix(np.zeros([10,401]))

In [60]:
theta.shape

(10, 401)

In [61]:
def computeCost(theta,X,y,alpha):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y= np.matrix(y)
    first =  np.multiply(-y,np.log(sigmoid(X*theta.T)))
    second = np.multiply((1-y),np.log(1-sigmoid(X*theta.T)))
    return (np.sum(first-second))/(len(X)) 

In [62]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [63]:
theta

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [64]:
import scipy.optimize as opt

In [65]:
def gradient(theta,X,y,alpha):
    parameters = 401
    X = np.matrix(X)
    theta = np.matrix(theta) 
    y = np.matrix(y)
    temp = np.zeros(parameters)
    error = sigmoid((X*theta.T))-y
    for j in range(parameters):
        term= np.multiply(error,X[:,j])
        temp[j] = (alpha*np.sum(term))/(len(X))
    return temp  

In [66]:
def onevsAll(X,y,alpha):
    num_label =  len(np.unique(y))
    rows = X.shape[0]
    params =X.shape[1]
    all_theta =np.matrix(np.zeros((num_label,params)))
    for i in range(1,num_label+1):
        theta  = np.zeros(params)
        y_i =  construct(i)
        y_i = np.reshape(y_i,(rows,1))
        result = opt.fmin_tnc(func=computeCost,x0=theta, fprime=gradient,args=(X,y_i,alpha))
        all_theta[i-1,:] = result[0]
        
    return all_theta     

In [67]:
def construct(i):
    y_o = np.zeros(5000).reshape(5000,1)
    for j in range(5000):
        if(y[j]==i):
            y_o[j]=1
        else:
            y_o[j]=0
    return y_o   
            

In [76]:
t1 = onevsAll(X,y,0.001)

C:\Users\ashish umrey\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  
C:\Users\ashish umrey\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in multiply
  


In [75]:
y = np.array(y)

In [77]:
t1

matrix([[ -7.10435381e+00,   0.00000000e+00,   0.00000000e+00, ...,
           1.36517989e-02,   2.86182207e-07,   0.00000000e+00],
        [ -5.48432931e+00,   0.00000000e+00,   0.00000000e+00, ...,
           4.65585215e-02,  -5.22195496e-03,   0.00000000e+00],
        [ -7.23357100e+00,   0.00000000e+00,   0.00000000e+00, ...,
          -2.53144251e-04,  -1.09217141e-06,   0.00000000e+00],
        ..., 
        [ -1.05000723e+01,   0.00000000e+00,   0.00000000e+00, ...,
          -1.26351103e-03,   1.30101024e-04,   0.00000000e+00],
        [ -8.33114952e+00,   0.00000000e+00,   0.00000000e+00, ...,
          -8.53504538e-02,   5.76963795e-03,   0.00000000e+00],
        [ -7.50818601e+00,   0.00000000e+00,   0.00000000e+00, ...,
           1.22951211e-03,   3.28432441e-05,   0.00000000e+00]])

In [78]:
t1.shape

(10, 401)

In [79]:
theta  = np.zeros(401)
computeCost(theta,X,construct(1),0.01)

0.6931471805599454

In [80]:
y

array([[10],
       [10],
       [10],
       ..., 
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)

In [81]:
final = sigmoid(X*t1.T)

In [82]:
final

matrix([[  5.61120020e-43,   1.14743045e-07,   1.44579221e-09, ...,
           1.44493123e-06,   2.62762129e-06,   9.99887176e-01],
        [  3.90859834e-35,   4.87753563e-11,   4.01302377e-08, ...,
           5.68555665e-08,   2.83380172e-13,   9.99995473e-01],
        [  4.02974190e-39,   3.65913123e-05,   2.69662330e-05, ...,
           8.14548231e-04,   1.74233310e-04,   9.99976631e-01],
        ..., 
        [  2.44685196e-04,   6.27930022e-06,   6.29123751e-01, ...,
           3.87701632e-04,   8.93920992e-01,   9.44905582e-11],
        [  6.75490140e-34,   2.88170815e-17,   2.28628923e-07, ...,
           1.41149000e-02,   8.89850679e-01,   4.03951422e-09],
        [  9.94713709e-53,   4.50148383e-13,   4.59606187e-14, ...,
           2.21275825e-02,   2.75678772e-01,   1.54273994e-03]])

In [1]:
np.argsmax(final[4999])

NameError: name 'np' is not defined

In [84]:
rows  = final.shape[0]
column =  final.shape[1]
predicted = np.matrix(np.zeros((rows,1)))
for i in range (rows):
    predicted[i,0]= np.argmax(final[i])+1

In [85]:
predicted

matrix([[ 10.],
        [ 10.],
        [ 10.],
        ..., 
        [  9.],
        [  9.],
        [  9.]])

In [86]:
rows = final.shape[0]
actual = y
count =0
for i in range(rows):
    if(predicted[i]== actual[i]):
        count = count +1

In [87]:
count

4860

In [88]:
4860/5000

0.972