In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
%matplotlib inline

In [2]:
data = loadmat("E:\MLNEW _BTM\data\ex3data1.mat")

In [3]:
data

{'X': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 'y': array([[10],
        [10],
        [10],
        ..., 
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [4]:
X= data['X']
y = data['y']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=50)

In [7]:
from sklearn.neural_network import MLPClassifier


In [27]:
mlp = MLPClassifier(activation='logistic',hidden_layer_sizes=(500), max_iter=1000)

In [28]:
mlp.fit(X_train,y_train.ravel())

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=500, learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [29]:
prediction = mlp.predict(X_test)

In [30]:
prediction

array([ 6,  4, 10, ...,  7,  3,  5], dtype=uint8)

In [31]:
pred = mlp.score(X_test,y_test)

In [32]:
pred

0.92533333333333334

In [33]:
pred2 = mlp.score(X_train,y_train)

In [34]:
pred2

1.0

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
prediction3 = mlp.predict(X_test)

In [19]:
prediction3

array([ 6,  4, 10, ...,  6,  2,  5], dtype=uint8)

In [20]:
print(confusion_matrix(y_test,prediction3))

[[143   1   3   2   1   0   3   1   0   0]
 [  0 117   2   1   3   4   1   9   0   1]
 [  3   4 125   0  11   0   4   4   1   1]
 [  0   1   0 117   1   8   1   0  13   0]
 [  0   1  11   1 119   2   0   7   1   0]
 [  0   0   0   3   0 148   0   0   0   8]
 [  4   1   3   1   0   0 143   1  18   0]
 [  2   1   4   0   6   0   2 128   1   0]
 [  1   1   1   9   3   3   9   2 129   0]
 [  0   1   0   0   3   5   0   0   0 131]]
