In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
%matplotlib inline

In [4]:
wine = pd.read_csv('E:\MLNEW _BTM\wine.csv',names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])

In [5]:
wine.head()

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [30]:
wine.describe()
X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=50)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((142, 13), (36, 13), (142,), (36,))

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler = StandardScaler()

In [35]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
X_train =  scaler.transform(X_train)
X_test  = scaler.transform(X_test)

In [19]:
X_train

array([[-0.32982876, -0.46525561, -0.63288254, ...,  0.88001708,
         0.77100262, -0.13931838],
       [-0.775647  ,  1.35316541,  0.03117648, ..., -1.73389504,
        -1.41388289, -0.74144307],
       [ 1.62681799, -0.36623268,  1.28551018, ...,  0.48793026,
         0.08472448,  1.61739591],
       ..., 
       [-1.70443502, -0.87935148,  1.21172585, ...,  0.00871304,
         0.93907074, -0.24484539],
       [-0.18122268,  0.56998408,  0.87969634, ..., -0.29624337,
        -0.61555934, -0.52418158],
       [ 0.22744405,  0.23690696, -0.00571569, ..., -1.55963423,
        -1.35786019,  0.25175229]])

In [37]:
from sklearn.neural_network import MLPClassifier


In [38]:
mlp = MLPClassifier(activation='logistic',hidden_layer_sizes=(13,13,13), max_iter=1000)

In [39]:
mlp.fit(X_train,y_train.ravel())

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [40]:
prediction = mlp.predict(X_test)

In [41]:
prediction

array([2, 2, 2, 3, 3, 3, 2, 2, 1, 3, 1, 1, 2, 1, 2, 3, 2, 3, 2, 1, 1, 2, 1,
       3, 1, 1, 2, 2, 1, 2, 1, 1, 3, 3, 1, 2], dtype=int64)

In [43]:
predict = mlp.score(X_test,y_test)
X_test.shape,y_test.shape
predict

1.0

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
prediction3 = mlp.predict(X_test)

In [46]:
print(confusion_matrix(y_test,prediction3))

[[13  0  0]
 [ 0 14  0]
 [ 0  0  9]]
